name: Python CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  linting:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pylint isort black pyright
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with black
      run: |
        black api --check
    - name: Lint with flake8
      run: |
        find api -maxdepth 2 -type f -name "*.py" | xargs flake8
    - name: Lint with pylint
      run: |
        find api -maxdepth 2 -type f -name "*.py" | xargs pylint --init-hook \
        "import sys; sys.path.append('./api')"
    - name: Lint with isort
      run: |
        isort api --check
